# Generated by Django 4.0.6 on 2022-07-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
