# Generated by Django 4.0.6 on 2022-07-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codersapp', '0002_alter_alumno_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fotoPerfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotoPerfil/'),
        ),
    ]
