# Generated by Django 4.0.6 on 2022-07-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codersapp', '0003_alter_alumno_fotoperfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
